name: Deploy to Lightsail Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app to Lightsail bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debugging: Print out the values of AWS credentials
      - name: Debug AWS Credentials
        run: |
          echo "AWS Access Key ID: ${{ secrets.AWS_BUCKET_ACCESS_KEY_ID }}"
          echo "AWS Secret Access Key: ${{ secrets.AWS_BUCKET_ACCESS_KEY }}"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_BUCKET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_BUCKET_ACCESS_KEY }}
          aws-region: ap-northeast-1 


      - name: Sync files to Lightsail bucket
        run: aws s3 sync . s3://bucket-f8ky00 --exclude '.git/*' --exclude '.github/*' --exclude '.ipynb_checkpoints/*' --exclude '__pycache__/*' --exclude '.gitignore' --exclude 'config.ini' --exclude 'Dockerfile'